// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Backend.Data;

#nullable disable

namespace Portfolio.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620180821_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Portfolio.Backend.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alt = "Fotografia techniczna 1",
                            Caption = "Labolatorium SpaceTeam AGH, Kraków",
                            Src = "/media/IMG_9783.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Alt = "Fotografia techniczna 2",
                            Caption = "Ale Kosmos!, PGE Narodowy, Warszawa",
                            Src = "/media/IMG_2868 (1).JPG"
                        },
                        new
                        {
                            Id = 3,
                            Alt = "Fotografia techniczna 3",
                            Caption = "Labolatorium SpaceTeam AGH, Kraków",
                            Src = "/media/IMG_9812.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Alt = "Fotografia techniczna 4",
                            Caption = "Kuchnia, Kielce",
                            Src = "/media/img1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Alt = "Fotografia techniczna 5",
                            Caption = "Jesień",
                            Src = "/media/20251109_132753 (1).jpg"
                        },
                        new
                        {
                            Id = 6,
                            Alt = "Fotografia techniczna 6",
                            Caption = "Sypialnia, Kielce",
                            Src = "/media/IMG_9722.JPG"
                        });
                });

            modelBuilder.Entity("Portfolio.Backend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumb")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoSrc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoSrcDe")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoSrcEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Projekt i wdrożenie wizytówki dla firmy zajmującej się monitoringiem konstrukcji przemysłowych.",
                            Link = "https://m-a-k.pl",
                            Subtitle = "Web Development",
                            Tags = "WordPress,HTML,CSS,PHP",
                            Thumb = "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
                            Title = "Monitoring Automatyczny Konstrukcji",
                            Type = "web",
                            VideoType = "placeholder"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Realizacja filmu promocyjnego. Wersja polska, angielska i niemiecka, przygotowana pod kampanie na stronie internetowej piecykigazowe.com.pl | Nagrania nie były częścią pracy mojego kamerzysty w tym projekcie.",
                            Subtitle = "Produkcja Wideo",
                            Tags = "Davinci Resolve Studio,Color Grading,Audio Mastering,Marketing,Dubbing AI w Wielu Językach,Tylko Postprodukcja",
                            Thumb = "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
                            Title = "Promocyjny Film – Piecyki Gazowe",
                            Type = "video",
                            VideoSrc = "/media/piecyki-pl.mp4",
                            VideoSrcDe = "/media/piecyki-de.mp4",
                            VideoSrcEn = "/media/piecyki-en.mp4",
                            VideoType = "local"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Wysokiej jakości inspekcje oraz materiały promocyjne z powietrza dla obiektów przemysłowych.",
                            Subtitle = "Ujęcia z Drona",
                            Tags = "Dron,Nagranie i Montaż",
                            Thumb = "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&q=80",
                            Title = "Ujęcia z Drona",
                            Type = "video",
                            VideoSrc = "/media/drone.mp4",
                            VideoType = "local"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Edukacyjny materiał wideo dotyczący technologii blockchain oraz kryptowalut.",
                            Subtitle = "Produkcja Wideo",
                            Tags = "Davinci Resolve Studio,Animacje",
                            Thumb = "https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=800&q=80",
                            Title = "Kryptowaluty – Film Informacyjny",
                            Type = "video",
                            VideoSrc = "https://www.youtube.com/embed/mUA6R7Ym_UQ?",
                            VideoType = "youtube"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Prezentacja nowego modułu awizacji faktur w systemie ERP dla firmy Infover.",
                            Subtitle = "Produkcja Wideo",
                            Tags = "Screencast,Animacje,Davinci Resolve Studio",
                            Thumb = "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
                            Title = "Awizacja Faktur ERP – Infover",
                            Type = "video",
                            VideoSrc = "/media/infover-erp.mp4",
                            VideoType = "local"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Umieszczenie koparki regolitu księżycowego w środowisku Wirtualnej Rzeczywistości w oparciu o silnik Unreal Engine 5.",
                            Subtitle = "Dokumentacja Wideo",
                            Tags = "Przedstawienie Projektu,Nagrania z Produkcji,Nagranie i Montaż",
                            Thumb = "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800&q=80",
                            Title = "Projekt VR – Unreal Engine 5",
                            Type = "video",
                            VideoSrc = "/media/SpejsyVR_v1.mp4",
                            VideoType = "local"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Międzynarodowa prezentacja projektu Distobee – zaawansowanej koparki regolitu księżycowego. Materiał w języku angielskim.",
                            Subtitle = "Produkcja Wideo",
                            Tags = "Nagrania z Produkcji,Engineering,English,Nagrania i Montaż",
                            Thumb = "https://images.unsplash.com/photo-1614729939124-032f0b56c9ce?w=800&q=80",
                            Title = "Distobee – Prezentacja (EN)",
                            Type = "video",
                            VideoSrc = "/media/distobee-en.mp4",
                            VideoType = "local"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Szczegółowy film ukazujący kulisy konstrukcji oraz działanie koparki regolitu księżycowego Distobee.",
                            Subtitle = "Produkcja Wideo",
                            Tags = "Nagrania z Produkcji,Engineering,Nagrania i Montaż",
                            Thumb = "https://images.unsplash.com/photo-1454789548928-9efd52dc4031?w=800&q=80",
                            Title = "Distobee – Projekt (PL)",
                            Type = "video",
                            VideoSrc = "/media/distobee-pl.mp4",
                            VideoType = "local"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
